# Generated by Django 6.0.5 on 2026-05-13 03:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='menucategory',
            name='default_status',
            field=models.ManyToManyField(blank=True, to='inventory.orderstatus'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='order_status',
            field=models.ManyToManyField(blank=True, related_name='order', to='inventory.orderstatus'),
        ),
    ]
