# Generated by Django 6.0.5 on 2026-05-13 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_orderstatus_menucategory_default_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='menu_category',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='menu_category',
            field=models.ManyToManyField(blank=True, related_name='items', to='inventory.menucategory'),
        ),
    ]
